### Login
POST https://mobi-app-api.herokuapp.com/users/login
Content-Type: application/json
Accept: application/json

{
    "username": "256706914861",
    "password": "#4006@MHC"
}

### Refresh Tokens
GET https://mobi-app-api.herokuapp.com/tokens/refresh
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjI1NjcwNjkxNDg2MSIsImlhdCI6MTYxODQwNjYyOCwiZXhwIjoxNjE5MDExNDI4fQ.zoi_eJxODvgSxpj74pqxQ79hbRM5AR_bGwozsAkW0VU

### Retrive Doctors
GET https://mobi-app-api.herokuapp.com/doctors
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjI1NjcwNjkxNDg2MSIsImlhdCI6MTYxODQwODkyOSwiZXhwIjoxNjE4NDA5MjI5fQ.5nRD-vGYie8A0ApPjflYlXLR-kNU4S5vMkS3YJllm1I