### Login
POST https://mobi-app-api.herokuapp.com/users/login
Content-Type: application/json
Accept: application/json

{
    "username": "256706914861",
    "password": "#4006@MHC"
}

### Refresh Tokens
GET https://mobi-app-api.herokuapp.com/tokens/refresh
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjI1NjcwNjkxNDg2MSIsImlhdCI6MTYzNTE2OTg1MSwiZXhwIjoxNjM3NzYxODUxfQ.sNrtCYUeF9sH8NCXjz431ccmFq4As6FCft108jEtOHI

### Retrive Doctors
GET https://mobi-app-api.herokuapp.com/doctors
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hbG9uZ2UiLCJpYXQiOjE2MzUxNjk5MjAsImV4cCI6MTYzNTc3NDcyMH0.QNCQ6UnZtzvfwkp0JIVPpocrUi5ovqd6W8M2cjsD5sc
### Localhost
POST http://localhost:4600/users/login
Content-Type: application/json
Accept: application/json

{
    "username": "256706914861",
    "password": "#4006@MHC"
}

### Get new route
GET http://localhost:4600/doctors
Content-Type: application/json
Accept: application/json