/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateHospitalArgs } from "./CreateHospitalArgs";
import { UpdateHospitalArgs } from "./UpdateHospitalArgs";
import { DeleteHospitalArgs } from "./DeleteHospitalArgs";
import { HospitalFindManyArgs } from "./HospitalFindManyArgs";
import { HospitalFindUniqueArgs } from "./HospitalFindUniqueArgs";
import { Hospital } from "./Hospital";
import { HospitalService } from "../hospital.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Hospital)
export class HospitalResolverBase {
  constructor(
    protected readonly service: HospitalService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Hospital",
    action: "read",
    possession: "any",
  })
  async _hospitalsMeta(
    @graphql.Args() args: HospitalFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Hospital])
  @nestAccessControl.UseRoles({
    resource: "Hospital",
    action: "read",
    possession: "any",
  })
  async hospitals(
    @graphql.Args() args: HospitalFindManyArgs
  ): Promise<Hospital[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Hospital, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Hospital",
    action: "read",
    possession: "own",
  })
  async hospital(
    @graphql.Args() args: HospitalFindUniqueArgs
  ): Promise<Hospital | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Hospital)
  @nestAccessControl.UseRoles({
    resource: "Hospital",
    action: "create",
    possession: "any",
  })
  async createHospital(
    @graphql.Args() args: CreateHospitalArgs
  ): Promise<Hospital> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Hospital)
  @nestAccessControl.UseRoles({
    resource: "Hospital",
    action: "update",
    possession: "any",
  })
  async updateHospital(
    @graphql.Args() args: UpdateHospitalArgs
  ): Promise<Hospital | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Hospital)
  @nestAccessControl.UseRoles({
    resource: "Hospital",
    action: "delete",
    possession: "any",
  })
  async deleteHospital(
    @graphql.Args() args: DeleteHospitalArgs
  ): Promise<Hospital | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
